<a href="https://colab.research.google.com/github/aly202012/py/blob/master/tensorflow_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf
import numpy as np


In [3]:
print(tf.__version__)

2.6.0


In [4]:
string=tf.Variable('tis is variaible', tf.string)

In [5]:
print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'tis is variaible'>


In [8]:
# constant
variable=tf.constant(4)

In [9]:
print(variable)

tf.Tensor(4, shape=(), dtype=int32)


In [10]:
var=tf.constant([2.0, 3.0, 4.0])

In [11]:
print(var)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [12]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [13]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.int16)

In [14]:
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int16)


In [22]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]]])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [23]:
print(rank_3_tensor[0])

tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)


In [21]:
print(rank_3_tensor[1])

tf.Tensor(
[[10 11 12 13 14]
 [15 16 17 18 19]], shape=(2, 5), dtype=int32)


In [24]:
print(rank_3_tensor[1,:])

tf.Tensor(
[[10 11 12 13 14]
 [15 16 17 18 19]], shape=(2, 5), dtype=int32)


In [26]:
print(rank_3_tensor[1,1:2,:2])

tf.Tensor([[15 16]], shape=(1, 2), dtype=int32)


In [34]:
a = tf.constant([[1, 2],
                 [3, 4]], dtype=tf.int16)
b = tf.constant([[1, 1],
                 [1, 1]], dtype=tf.int16)


In [35]:
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int16)


In [40]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [41]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [42]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

In [43]:
print(c)

tf.Tensor(
[[ 4.  5.]
 [10.  1.]], shape=(2, 2), dtype=float32)


In [45]:
# Find the largest value
print(tf.reduce_max(rank_3_tensor))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(29, shape=(), dtype=int32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [51]:
vec=tf.zeros([3, 2, 4, 5])

In [52]:
print(vec)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)


In [53]:
print(vec.shape)

(3, 2, 4, 5)


In [54]:
print(rank_2_tensor[1, 1].numpy())

4


In [56]:
print(rank_3_tensor[:, :, 3])

tf.Tensor(
[[ 3  8]
 [13 18]
 [23 28]], shape=(3, 2), dtype=int32)


In [57]:
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])

In [65]:
print(tf.slice(t1,
               begin=[4],
               size=[4]))

tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)


In [63]:
print(t1)

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)


In [66]:
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [67]:
print(x)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [68]:
print(tf.reshape(rank_3_tensor, [3*2, 5]), "\n")

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 



In [69]:
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


In [70]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [71]:
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [72]:
print(y)

tf.Tensor(2, shape=(), dtype=int32)


In [73]:
print(z)

tf.Tensor([2 2 2], shape=(3,), dtype=int32)


In [74]:
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [77]:
print(tf.broadcast_to(tf.constant([1, 2, 3, 4]), [3, 4]))

tf.Tensor(
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]], shape=(3, 4), dtype=int32)


In [78]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [79]:
print(ragged_list)

[[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]


In [80]:
print(ragged_list[1])

[4, 5]


In [81]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [84]:
stre=tf.constant('ali mohammed')
print(stre)

tf.Tensor(b'ali mohammed', shape=(), dtype=string)


In [87]:
# If you have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In [88]:
print(tensor_of_strings[0])

tf.Tensor(b'Gray wolf', shape=(), dtype=string)
